export const FETCH_CURRENCY = 'FETCH_CURRENCY';
export const PENDING_CURRENCY = 'PENDING_CURRENCY';
export const GET_CURRENCY = 'GET_CURRENCY';
export const FETCH_TIMESERIES = 'FETCH_TIMESERIES';
export const PENDING_TIMESERIES = 'PENDING_TIMESERIES';
export const GET_TIMESERIES = 'GET_TIMESERIES';
export const SET_TARGET_CURRENCY = 'SET_TARGET_CURRENCY';
export const TOGGLE_CHART = 'TOGGLE_CHART';
